version: "3.6"

services:
  auth-postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=my_database
    volumes:
      - "C:/Users/nikra/Desktop/whats_better_web/core/postresql/data:/var/lib/postgresql/data"
    ports:
      - "15432:5432"