log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: whats_better_network1
    exposedbydefault: false

entrypoints:
  http:
    address: :80
  https:
    address: :443

accesslog: true